// Writing the calibration script's solution back out as a bundle file (spec B.1).
//
// It is a separate, generated file rather than an edit to the authored YAML so that
// "which of these numbers did a human choose?" has an answer you can see. Rewriting
// milestones.yaml in place would put solved and authored numbers in the same file
// with nothing to tell them apart, which is the state B.1 exists to prevent.
import { stringify } from "yaml";
import type { Derived } from "./schema.js";

const HEADER = `# GENERATED by \`pnpm sim calibrate --write\`. Do not hand-edit: the next run
# overwrites it, and a number edited here is a number nobody measured.
#
# Spec B.1 -- intent is authored, numbers are solved. The authored files next to this
# one still carry amounts and cost ratios; on a calibrated bundle those are the seeds
# the search started from, and these are what the game runs on. \`loadBundleDir\` lays
# this block over them, so everything downstream sees one bundle and none of it can
# be looking at the seeds by accident.
#
# \`run\` is the reviewable claim, not an input: nothing reads it at runtime. It says
# what this run aimed at and what these numbers actually measured, so a bundle whose
# observed column has drifted from its target column is visibly stale.
`;

/**
 * Deterministic: same solution in, byte-identical file out, so a re-run over
 * unchanged content diffs to nothing but the timestamp and whatever actually moved.
 */
export function serialiseDerived(derived: Derived): string {
  const ordered: Derived = {
    ...(derived.run !== undefined ? { run: derived.run } : {}),
    ...(derived.machineClasses !== undefined
      ? { machineClasses: [...derived.machineClasses].sort((a, b) => (a.id < b.id ? -1 : 1)) }
      : {}),
    ...(derived.milestones !== undefined
      ? { milestones: [...derived.milestones].sort((a, b) => a.tier - b.tier) }
      : {}),
    ...(derived.storage !== undefined ? { storage: derived.storage } : {}),
    ...(derived.quantumStorage !== undefined ? { quantumStorage: derived.quantumStorage } : {}),
  };
  return `${HEADER}${stringify({ derived: ordered }, { nullStr: "null" })}`;
}
